all:
  children:
    mysql:
      hosts:
        ls-db:
          ansible_host: 192.168.56.11
    tokenization:
      hosts:
        ls-token:
          ansible_host: 192.168.56.12
          mysql_vm_ip: 192.168.56.11
    private_api:
      hosts:
        ls-api:
          ansible_host: 192.168.56.13
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/lifesync360-onprem.pem
    ansible_python_interpreter: /usr/bin/python3
